apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default

  source:
    repoURL: https://github.com/HigherGround189/icantkube.git
    targetRevision: main
    path: kubernetes/secrets
    directory:
      recurse: true
      include: "*.sealed.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
